from . import views
from django.conf.urls import url

app_name = 'login'
urlpatterns = [
    # url(r'^upload/', views.upload_csv, name="upload"),
    url(r'^app/', views.index_view, name="index"),
    url(r'^home/', views.home_view, name="home"),
    url(r'^login/', views.login_view, name="login"),
    url(r'^logout/', views.logout_view, name="logout"),
    url(r'^register/', views.register_view, name="register"),
    url(r'^profile/', views.profile_view, name="profile"),
    url(r'^profile1/', views.wifi_view),
    url(r'^profile2/', views.civil_view),
    url(r'^profile3/', views.electric_view),
    url(r'^profile4/', views.mechanic_view),
    url(r'^profile5/', views.other_view),
    url(r'^civillocations/$', views.display_civil_location),
    url(r'^wifilocations/$', views.display_wifi_location),
    url(r'^otherlocations/$', views.display_other_location),
    url(r'^electriclocations/$', views.display_electric_location),
    url(r'^location/$', views.loc_view),
    url(r'^wifidata/$', views.wifi_work_data),
    url(r'^draingeworker/$', views.wifi_worker_view),
    url(r'^garbageworker/$', views.civil_worker_view),
    url(r'^electricworker/$', views.electric_worker_view),
    url(r'^otherworker/$', views.other_worker_view),
    url(r'^data/$', views.wifi_work_data),
    url(r'^data11/$', views.admin_wifi_data),
    url(r'^data12/$', views.admin_civil_data),
    url(r'^data13/$', views.admin_electric_data),
    url(r'^data14/$', views.admin_other_data),
    url(r'^loct/$', views.loct),
    url(r'^wff/$', views.wifi_worker_comp),
    url(r'^cw/$', views.civil_worker_comp),
    url(r'^ew/$', views.electric_worker_comp),
    url(r'^ow/$', views.other_worker_comp),
    url(r'^profile222/$', views.wifi_worker_inp),
    url(r'^profile111/$', views.wifi_worker_complete_status),
    url(r'^profile444/$', views.user_status_wifi_completed),
    url(r'^profile555/$', views.user_status_wifi_inprogress),
    url(r'^profile777/$', views.user_status_civil_inprogress),
    url(r'^profile888/$', views.user_status_civil_completed),
    url(r'^profile999/$', views.user_status_electric_inprogress),
    url(r'^profile789/$', views.user_status_electric_completed),
    url(r'^profile879/$', views.user_status_other_inprogress),
    url(r'^profile998/$', views.user_status_other_completed),
    url(r'^status/$', views.st_view),
    url(r'^wifi/$', views.wf_view),
    url(r'^civil/$', views.cv_view),
    url(r'^electric/$', views.el_view),
    url(r'^other/$', views.ot_view),
    url(r'^profile222/$', views.other_worker_inp),
    url(r'^profile222/$', views.civil_worker_inp),
    url(r'^profile222/$', views.electric_worker_inp),
    url(r'^cvv/$', views.civil_worker_complete_status),
    url(r'^ecc/$', views.electric_worker_complete_status),
    url(r'^ott/$', views.other_worker_complete_status),
    url(r'^resetpass/$', views.reset_password)
    

]