# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20170914_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilename',
            name='name',
        ),
        migrations.DeleteModel(
            name='UserProfilename',
        ),
    ]
