# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20170914_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomplaint',
            name='Mobile_number',
            field=models.IntegerField(),
        ),
    ]
