# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-16 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0024_userothercomplaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilComplaintDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('location', models.CharField(default='Null', max_length=200)),
                ('Mobile_number', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('first_name', models.CharField(default='Null', max_length=200)),
                ('worker_Mobile_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CivilComplaintWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Null', max_length=200)),
                ('middle_name', models.CharField(default='Null', max_length=200)),
                ('last_name', models.CharField(default='Null', max_length=200)),
                ('Mobile_number', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricComplaintDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('location', models.CharField(default='Null', max_length=200)),
                ('Mobile_number', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('first_name', models.CharField(default='Null', max_length=200)),
                ('worker_Mobile_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricComplaintWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Null', max_length=200)),
                ('middle_name', models.CharField(default='Null', max_length=200)),
                ('last_name', models.CharField(default='Null', max_length=200)),
                ('Mobile_number', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='OtherComplaintDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('location', models.CharField(default='Null', max_length=200)),
                ('Mobile_number', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('first_name', models.CharField(default='Null', max_length=200)),
                ('worker_Mobile_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherComplaintWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Null', max_length=200)),
                ('middle_name', models.CharField(default='Null', max_length=200)),
                ('last_name', models.CharField(default='Null', max_length=200)),
                ('Mobile_number', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='WifiComplaintDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='some string', max_length=200)),
                ('user_complaint', models.CharField(max_length=200)),
                ('user_location', models.CharField(default='Null', max_length=200)),
                ('user_Mobile_number', models.IntegerField()),
                ('worker_name', models.CharField(default='Null', max_length=200)),
                ('last_name', models.CharField(default='Null', max_length=200)),
                ('worker_Mobile_number', models.IntegerField(null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='WifiComplaintWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Null', max_length=200)),
                ('middle_name', models.CharField(default='Null', max_length=200)),
                ('last_name', models.CharField(default='Null', max_length=200)),
                ('Mobile_number', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='userwificomplaint',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userwificomplaint',
            name='Mobile_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wificomplaintdetails',
            name='WifiComplaintWorker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.WifiComplaintWorker'),
        ),
        migrations.AddField(
            model_name='wificomplaintdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='othercomplaintdetails',
            name='WifiComplaintWorker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.WifiComplaintWorker'),
        ),
        migrations.AddField(
            model_name='othercomplaintdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electriccomplaintdetails',
            name='WifiComplaintWorker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.WifiComplaintWorker'),
        ),
        migrations.AddField(
            model_name='electriccomplaintdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='civilcomplaintdetails',
            name='WifiComplaintWorker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.WifiComplaintWorker'),
        ),
        migrations.AddField(
            model_name='civilcomplaintdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
