# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-20 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_auto_20171217_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='wificomplaintdetails',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
