# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-20 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_wificomplaintdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwificomplaint',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
