# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-20 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0028_userwificomplaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wificomplaintworker',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
