# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_auto_20171220_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wificomplaintworker',
            name='user',
        ),
        migrations.AddField(
            model_name='userwificomplaint',
            name='bulding_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userwificomplaint',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userwificomplaint',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
    ]
