# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_auto_20171221_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwificomplaint',
            name='email',
        ),
    ]
