# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_remove_userwificomplaint_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwificomplaint',
            name='bulding_name',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
