# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_auto_20171221_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwificomplaint',
            name='bulding_name',
        ),
        migrations.RemoveField(
            model_name='userwificomplaint',
            name='room_number',
        ),
    ]
