# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_auto_20171221_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wificomplaintworker',
            name='first_name',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
