# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_auto_20171221_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwificomplaint',
            name='bulding_name',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='userwificomplaint',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
    ]
