# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0038_userwificomplaint_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilcomplaintworker',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='electriccomplaintworker',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='othercomplaintworker',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usercivilcomplaint',
            name='bulding_name',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='usercivilcomplaint',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usercivilcomplaint',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userelectriccomplaint',
            name='bulding_name',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='userelectriccomplaint',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userelectriccomplaint',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usermachanicalcomplaint',
            name='bulding_name',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='usermachanicalcomplaint',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usermachanicalcomplaint',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userothercomplaint',
            name='bulding_name',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='userothercomplaint',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userothercomplaint',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wificomplaintdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='wificomplaintworker',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
