# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_auto_20171221_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilcomplaintdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='civilcomplaintdetails',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electriccomplaintdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='electriccomplaintdetails',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='othercomplaintdetails',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='othercomplaintdetails',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercivilcomplaint',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userelectriccomplaint',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermachanicalcomplaint',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userothercomplaint',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
