# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-22 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0040_auto_20171221_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercivilcomplaint',
            name='bulding_name',
            field=models.TextField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='usercivilcomplaint',
            name='room_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userelectriccomplaint',
            name='bulding_name',
            field=models.TextField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='userelectriccomplaint',
            name='room_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usermachanicalcomplaint',
            name='bulding_name',
            field=models.TextField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='usermachanicalcomplaint',
            name='room_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userothercomplaint',
            name='bulding_name',
            field=models.TextField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='userothercomplaint',
            name='room_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userwificomplaint',
            name='bulding_name',
            field=models.TextField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='userwificomplaint',
            name='room_number',
            field=models.TextField(null=True),
        ),
    ]
